### PR TITLE
Fix regex for DCQCN

### PR DESCRIPTION
**Pull request by velomatt**
- skip task if regex does not match
- won't fail if the regex doesn't match now

### CODE REVIEW

**Comment by velomatt** [comment]
Low risk changes. Only applies to `configure_vlans` play.

Was previously failing when attempting to configure a host with ConnectX 4 adapters. Now those adapters will be skipped and not fail with a cryptic error.

**Comment by mssawant** [comment]
@velomatt , trying to understand the problem and the solution, since we needed to add the connectX-4 adapters before, why are we silently skipping them now?

[suggestion] I think, ```Was previously failing when attempting to configure a host with ConnectX 4 adapters. Now those adapters will be skipped and not fail with a cryptic error.``` would help to be part of the commit message problem statement.

**Comment by velomatt** [comment]
> @velomatt , trying to understand the problem and the solution, since we needed to add the connectX-4 adapters before, why are we silently skipping them now?
> 
> [suggestion] I think, `Was previously failing when attempting to configure a host with ConnectX 4 adapters. Now those adapters will be skipped and not fail with a cryptic error.` would help to be part of the commit message problem statement.

This bugfix is not specific to ConnectX 4 adapters, I'm just giving an example of where I encountered this error. This error can potentially happen with any Mellanox adapter if it does not have the specific DCQCN parameters we are tuning for maximum performance.

**Review by snubatreus — APPROVED** [review]
Looks good 👍

**Pull request merged**
