### PR TITLE
Add download_artifacts playbook and role

### PR DESCRIPTION
**Pull request by velomatt**
- Allows automatic download of latest artifacts from public s3
- by default master branch artifacts are downloaded
- s3 url can be overridden
- branch name can be overridden

### CODE REVIEW

**Comment by velomatt** [comment]
- Tested on intranet from public AWS S3 URL, `master` branch (default)
- Tested on intranet from public AWS S3 URL, `stable/v1.0` branch (override)
- Tested in lab network from local MinIO S3 URL, `master` branch (override)
- Tested in lab network from local MinIO S3 URL, `feature/value-add` branch (override)
- Tested idempotency (eg - downloads artifact only if not already present in `artifacts` directory)

**Review by snubatreus — DISMISSED** [review]
Looks good

**Review by nsarras — DISMISSED** [review]
looks good! Do we want to also add the role into the deployment playbook?

**Comment by velomatt** [comment]
> 

I think this is a good idea. But if I do that, I think it would make sense to be able to optionally not download (eg - if I want to deploy custom artifacts I already have in my `artifacts` directory). I will check in those changes shortly for your review.

**Comment by velomatt** [comment]
Demonstration of `download_artifacts` override behavior:

image

**Comment by nsarras** [comment]
yes that works! great option to have

> Demonstration of `download_artifacts` override behavior:
> 
> image

**Review by nsarras — APPROVED** [review]

**Pull request merged**
